name: Build All Platforms

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --------------------
  # Windows x64
  # --------------------
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Image (Windows)
        run: ./gradlew nativeCompile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: multi-windows
          path: build/native/nativeCompile/multi.exe


  # --------------------
  # Linux x64
  # --------------------
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          distribution: graalvm
          java-version: '21'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Make Gradle executable
        run: chmod +x gradlew

      - name: Build Native Image (Linux)
        run: ./gradlew nativeCompile

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: multi-linux-x64
          path: build/native/nativeCompile/multi